# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ed00385b449ac0602df1cdeaf77fff86aa4354f26019d5d7a87dd7a5fbb4579fe787705ff5a51ba62b423cdda79f98ee70b49d5355156ce1d51e7e304bc0d9af

test:
  secret_key_base: 65b147972447373c7d94b17b8812663437fb57fa3c78a9b75d82dc3d03318b93f0e99fd46c96dd20fc06d8b7e72eea70e9f4f2df48e5b6258d2ed883f80440d3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
